---
title: "Visualizing Information"
subtitle: "EMSE 4572: Exploratory Data Analysis"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# install.packages("cowplot")

library(tidyverse)
library(here)
library(cowplot)
knitr::opts_chunk$set(
    warning = FALSE,
    message = FALSE,
    fig.path = "figs/",
    fig.width = 7.252,
    fig.height = 4,
    comment = "#>",
    fig.retina = 3
)

# Read in data
gapminder <- read_csv(here('data', 'gapminder.csv'))
View(gapminder)
```


```{r americasLifeExp, fig.width=10, fig.height=7}
# Insert code here

prepared_data <- gapminder %>% 
    filter(year==2007, continent=="Americas") %>% 
    arrange(desc(lifeExp))

View(prepared_data)
```
# Practice making a good chart with ggplot

Use the `gapminder.csv` data to create the following plot, following these steps:

1. Format data frame
2. Add geoms
3. Flip coordinates?
4. Reorder factors?
5. Adjust scales
6. Adjust theme
7. Annotate

```{r americasLifeExp, fig.width=10, fig.height=7}

install.packages("ggtext")
library(ggtext)


prepared_data %>% 
    ggplot(
        #aes(x=lifeExp, y=country),
        #aes(y=reorder(country, lifeExp), x=lifeExp)
    ) + 
    geom_col(
        aes(y=reorder(country, lifeExp), x=lifeExp)
    ) +
    labs(
        title = "Life expectency by country (2007, Americas)",
        x = "Life Exp",
        y  = "Country",
    ) +
    ggtitle("<span style='font-size: 22pt;'>This is bigger text</font>") +
    theme(plot.title = element_markdown())


```
